os: linux
dist: xenial
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - "$HOME/.composer/cache"

jobs:
  include:
    # Run against Ubuntu 18.04 to test with openssl v1.1.1.
    - dist: bionic
      php: 7.1
      env: OPENSSL_VERSION=1.1.1
    - dist: bionic
      php: 7.2
      env: OPENSSL_VERSION=1.1.1
    - dist: bionic
      php: 7.3
      env: OPENSSL_VERSION=1.1.1
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer install --no-scripts --no-suggest --no-interaction

script:
  - vendor/bin/phpunit